prefill with github variables

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -41,6 +41,35 @@ include:
   - local: ".gitlab/benchmarks/serverless.yml"
   - local: ".gitlab/native.yml"
 
+github variables:
+  image: registry.ddbuild.io/images/dd-octo-sts-ci-base:2025.06-1
+  tags: [ "arch:amd64" ]
+  stage: .pre
+  id_tokens:
+    DDOCTOSTS_ID_TOKEN:
+      aud: dd-octo-sts
+  script:
+    - |
+      if [ -z ${GH_TOKEN} ]
+      then
+        # Use dd-octo-sts to get GitHub token
+        dd-octo-sts token --scope DataDog/dd-trace-py --policy gitlab.github-access.read > token
+        gh auth login --with-token < token
+        rm token
+      fi
+    - |
+      # Prevent git operation errors:
+      #   failed to determine base repo: failed to run git: fatal: detected dubious ownership in repository at ...
+      git config --global --add safe.directory "${CI_PROJECT_DIR}"
+    - |
+      # Determine if we have an open GitHub PR for this commit
+      GH_PR_NUMBER=$(gh pr list --search "${CI_COMMIT_REF_NAME}"--json number --jq '.[0].number' || echo "")
+      echo "GH_PR_NUMBER=${GH_PR_NUMBER}" >> workflow.env
+      echo "GH_PR_OPEN=$(if [ -z "${GH_PR_NUMBER}" ]; then echo "false"; else echo "true"; fi)" >> workflow.env
+  artifacts:
+    reports:
+      dotenv: workflow.env
+
 tests-gen:
   stage: tests
   extends: .testrunner
@@ -101,9 +130,20 @@ microbenchmarks:
             PYTHON_TAG: "cp39-cp39"
             LINUX_OS_IMAGE: "manylinux2014"
   rules:
+    # Allow failures if explicitly asked
     - if: $RELEASE_ALLOW_BENCHMARK_FAILURES == "true"
       allow_failure: true
-    - allow_failure: false
+    # Always run on PRs, tagged releases, and main or release branches
+    - if: $GH_PR_OPEN == "true"
+      when: always
+    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/
+      when: always
+    - if: $CI_COMMIT_BRANCH == "main"
+      when: always
+    - if: $CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+$/
+      when: always
+    # Otherwise, run manually
+    - when: manual
   trigger:
     include: .gitlab/benchmarks/microbenchmarks.yml
     strategy: depend
@@ -130,10 +170,17 @@ macrobenchmarks:
     DD_DISABLE_VPA: true
   allow_failure: true
   rules:
-    - if: $CI_PIPELINE_SOURCE == "schedule"
-      when: always
+    # Allow failures if explicitly asked
+    - if: $RELEASE_ALLOW_BENCHMARK_FAILURES == "true"
+      allow_failure: true
+    # Always run on tagged releases, and main or release branches
     - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+/
       when: always
+    - if: $CI_COMMIT_BRANCH == "main"
+      when: always
+    - if: $CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+$/
+      when: always
+    # Otherwise, run manually
     - when: manual
 
 check_new_flaky_tests:
