try CI_PROJECT_DIR

diff --git a/.gitlab/native.yml b/.gitlab/native.yml
--- a/.gitlab/native.yml
+++ b/.gitlab/native.yml
@@ -24,5 +24,5 @@ include:
     - |
       echo -e "\e[0Ksection_start:`date +%s`:check_events_pyi[collapsed=true]\r\e[0Kcheck events.pyi"
       cargo build
-      git -C ../.. diff --exit-code ddtrace/internal/events.pyi || (echo "Error: events.pyi is out of date. Run 'cargo build' in src/native/ and commit the changes." && exit 1)
+      git -C "$CI_PROJECT_DIR" diff --exit-code ddtrace/internal/events.pyi || (echo "Error: events.pyi is out of date. Run 'cargo build' in src/native/ and commit the changes." && exit 1)
       echo -e "\e[0Ksection_end:`date +%s`:check_events_pyi\r\e[0K"
