chore: infer remote name in backport script (#5302)
This change ensures that the correct remote is used to create backport
PRs.

diff --git a/scripts/backport b/scripts/backport
--- a/scripts/backport
+++ b/scripts/backport
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 if ! which gh &>/dev/null;
 then
    echo "gh cli tool is required in order to continue"
@@ -19,6 +21,9 @@ fi
 PR_NUMBER="${1}"
 shift 1
 TO_BRANCHES="$@"
+
+# Determine the remote to use
+git remote -v show | grep "https://github.com/[Dd]ata[Dd]og/dd-trace-py (push)" | read REMOTE _
 
 usage () {
     echo "Usage:"
@@ -78,14 +83,18 @@ original_labels="$(echo "${pr_data}" | jq -r '[.labels[].name] | join(",")')"
 current_branch="$(git rev-parse --abbrev-ref HEAD)"
 
 # Try to make sure we have the latest data from remote
-git fetch &>/dev/null || true
+git fetch --all &>/dev/null || true
 
 for base_branch in "$@";
 do
   echo "Backporting ${PR_NUMBER} (sha: ${merge_commit_sha}) to ${base_branch}"
   branch_name="backport-${PR_NUMBER}-to-${base_branch}"
-  git switch --detach "origin/${base_branch}"
-  git switch -c "${branch_name}"
+  if ! git switch --detach "${REMOTE}/${base_branch}"
+  then
+    echo "🟠 Cannot switch to base branch ${base_branch}, skipping ..."
+    continue
+  fi
+  git switch -C "${branch_name}"
 
   echo "Cherry-picking ${merge_commit_sha} (git commit signing required here)"
   if ! git cherry-pick -x "${merge_commit_sha}";
@@ -99,13 +108,13 @@ do
       exit 1
   fi
   echo "Pushing branch ${branch_name}"
-  git push --set-upstream origin "${branch_name}"
+  git push --set-upstream ${REMOTE} "${branch_name}"
 
   echo "Creating pull request"
-  IFS='' read -r -d '' new_body <<EOF
-  Backport of #${PR_NUMBER} to ${base_branch}
+  IFS='' read -r -d '' new_body <<EOF || true
+Backport of #${PR_NUMBER} to ${base_branch}
 
-  ${original_body}
+${original_body}
 EOF
   new_title="${original_title} [backport #${PR_NUMBER} to ${base_branch}]"
   gh pr create --base "${base_branch}" --title "${new_title}" --body "${new_body}" --assignee "@me,${original_author}" --label "${original_labels}"
@@ -121,3 +130,5 @@ EOF
   git switch "${current_branch}"
   git branch -D "${branch_name}"
 done
+
+echo "✨ 🍰 ✨ All done! ✨ 🍰 ✨"
