debug

diff --git a/.github/workflows/backport-validate.yml b/.github/workflows/backport-validate.yml
--- a/.github/workflows/backport-validate.yml
+++ b/.github/workflows/backport-validate.yml
@@ -32,7 +32,11 @@ jobs:
           TARGET_BRANCH=$(echo "${BACKPORT_LABEL}" | awk '{ print $NF }')
           MERGE_COMMIT=$(git rev-parse HEAD)
           git checkout origin/${TARGET_BRANCH}
-          CHERRYPICK_OUT=$(git cherry-pick -x --mainline 1 ${MERGE_COMMIT} 2>cherrypickerror.txt) || cat cherrypickerror.txt
+          echo "cherrypicking"
+          git cherry-pick -x --mainline 1 ${MERGE_COMMIT} 2>cherrypickerror.txt
+          echo "cherrypicking with capture"
+          CHERRYPICK_OUT=$(git cherry-pick -x --mainline 1 ${MERGE_COMMIT} 2>cherrypickerror.txt) || true
+          echo "grabbing error"
           ERROR=$(grep -v '^hint' cherrypickerror.txt)
 
           echo "results<<EOF" >> "$GITHUB_OUTPUT"
