fixed dependencies errors for bottle

diff --git a/.github/workflows/Bottle.yml b/.github/workflows/Bottle.yml
--- a/.github/workflows/Bottle.yml
+++ b/.github/workflows/Bottle.yml
@@ -23,8 +23,18 @@ jobs:
           repository: bottlepy/bottle
           ref: 0.12.19
           path: bottle
-      - name: Install dependencies
-        run: .github/workflows/install-deps.sh
+      - name: Install pytest
+        run: pip install -U pip pytest coverage
+      - name: Install Dependencies
+        run: sudo apt-get install -y libev-dev
+      - name: Install further dependencies
+        run: pip install mako jinja2
+      - name: Test dependencies (Server back-ends and template engines)
+        run: |
+          for name in waitress "cherrypy<9" cheroot paste tornado twisted diesel meinheld\
+            gunicorn eventlet flup bjoern gevent aiohttp-wsgi uvloop; do
+            pip install $name || echo "Failed to install $name with $(python -V 2>&1)" 1>&2
+          done
       - name: Inject ddtrace
         run: pip install ../ddtrace
       - name: Run tests
